// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mims.Data;

#nullable disable

namespace mims.Migrations
{
    [DbContext(typeof(ArtifactContext))]
    [Migration("20240520030418_NullableField")]
    partial class NullableField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mims.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("artifact_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("DateOfAquisition")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_aquisition");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EstimatedValue")
                        .HasColumnType("longtext")
                        .HasColumnName("estimated_value");

                    b.Property<string>("Inscription")
                        .HasColumnType("longtext")
                        .HasColumnName("inscription");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Measurement")
                        .HasColumnType("longtext")
                        .HasColumnName("measurement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("NameOfArtist")
                        .HasColumnType("longtext")
                        .HasColumnName("name_of_artist");

                    b.Property<string>("NameOfDonor")
                        .HasColumnType("longtext")
                        .HasColumnName("name_of_donor");

                    b.Property<string>("Number")
                        .HasColumnType("longtext")
                        .HasColumnName("number_of_object");

                    b.Property<string>("Period")
                        .HasColumnType("longtext")
                        .HasColumnName("period");

                    b.Property<string>("PhotoNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("photo_no");

                    b.Property<string>("PhysicalCondition")
                        .HasColumnType("longtext")
                        .HasColumnName("physical_condition");

                    b.Property<string>("PlaceOfOrigin")
                        .HasColumnType("longtext")
                        .HasColumnName("place_of_origin");

                    b.Property<string>("PlaceOfReceipt")
                        .HasColumnType("longtext")
                        .HasColumnName("place_of_receipt");

                    b.Property<string>("SignatureOfReceiver")
                        .HasColumnType("longtext")
                        .HasColumnName("signature_of_receiver");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_date");

                    b.Property<string>("UsedMaterial")
                        .HasColumnType("longtext")
                        .HasColumnName("used_matriel");

                    b.Property<string>("Weight")
                        .HasColumnType("longtext")
                        .HasColumnName("weight");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.ToTable("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
